FROM --platform=$BUILDPLATFORM golang:1.26-alpine AS builder

WORKDIR /src
ARG TARGETOS=linux
ARG TARGETARCH

RUN apk add --no-cache ca-certificates git

RUN mkdir -p /out \
    && CGO_ENABLED=0 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH:-$(go env GOARCH)} \
    go install github.com/pressly/goose/v3/cmd/goose@latest \
    && cp "$(go env GOPATH)/bin/goose" /out/goose

FROM alpine:3.23 AS runner

WORKDIR /app

RUN apk add --no-cache ca-certificates

COPY --from=builder /out/goose /usr/local/bin/goose
COPY db/migrations /migrations

ENTRYPOINT ["/bin/sh", "-c"]
CMD ["/usr/local/bin/goose -dir /migrations postgres \"$DB_CONN\" up"]
