FROM node:24-alpine AS builder
WORKDIR /app

# Install deps
COPY frontend/package*.json ./
RUN npm install

# Build
COPY frontend .
RUN npm run build

FROM nginx:1.27-alpine
WORKDIR /usr/share/nginx/html

COPY --from=builder /app/dist ./

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
