FROM --platform=$BUILDPLATFORM golang:1.26.0-alpine3.23 AS builder

WORKDIR /opt/app
ARG TARGETOS=linux
ARG TARGETARCH
RUN apk add --no-cache git ca-certificates
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH:-$(go env GOARCH)} \
    go build -o /opt/app/bin/api ./cmd/api

FROM gcr.io/distroless/static:nonroot
WORKDIR /opt/app
COPY --from=builder /opt/app/bin/api /opt/app/bin/api
ENV API_PORT=4040
ENV DB_CONN="postgres://ipam:ipam@localhost:5432/ipam?sslmode=disable"
EXPOSE ${API_PORT}
USER nonroot:nonroot
ENTRYPOINT [ "/opt/app/bin/api" ]
