FROM golang:1.25-alpine AS runner

WORKDIR /app

RUN apk add --no-cache ca-certificates git

# Install goose
RUN go install github.com/pressly/goose/v3/cmd/goose@latest

# Copy migrations
COPY db/migrations /migrations

ENTRYPOINT ["/bin/sh", "-c"]
CMD ["/go/bin/goose -dir /migrations postgres \"$DB_CONN\" up"]
