// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ip_addresses.sql

package db

import (
	"context"
	"net/netip"
)

const createIPAddress = `-- name: CreateIPAddress :one
INSERT INTO ip_addresses (ip, hostname, subnet_id)
VALUES ($1, $2, $3)
RETURNING id, ip, hostname, created_at, updated_at, subnet_id
`

type CreateIPAddressParams struct {
	Ip       netip.Addr `json:"ip"`
	Hostname string     `json:"hostname"`
	SubnetID int64      `json:"subnet_id"`
}

func (q *Queries) CreateIPAddress(ctx context.Context, arg CreateIPAddressParams) (IpAddress, error) {
	row := q.db.QueryRow(ctx, createIPAddress, arg.Ip, arg.Hostname, arg.SubnetID)
	var i IpAddress
	err := row.Scan(
		&i.ID,
		&i.Ip,
		&i.Hostname,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SubnetID,
	)
	return i, err
}

const listIPsBySubnetID = `-- name: ListIPsBySubnetID :many
SELECT id, ip, hostname, created_at, updated_at, subnet_id
FROM ip_addresses
WHERE subnet_id = $1
ORDER by ip
`

func (q *Queries) ListIPsBySubnetID(ctx context.Context, subnetID int64) ([]IpAddress, error) {
	rows, err := q.db.Query(ctx, listIPsBySubnetID, subnetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IpAddress
	for rows.Next() {
		var i IpAddress
		if err := rows.Scan(
			&i.ID,
			&i.Ip,
			&i.Hostname,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SubnetID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
