// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: kubernetes_discovery.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createKubernetesServiceAddress = `-- name: CreateKubernetesServiceAddress :exec
INSERT INTO kubernetes_service_addresses (
    service_id, kind, address, ip_mode, ip_address_id, match_status, match_count
) VALUES ($1, $2, $3, NULLIF($4, ''), $5, $6, $7)
`

type CreateKubernetesServiceAddressParams struct {
	ServiceID   pgtype.UUID `json:"service_id"`
	Kind        string      `json:"kind"`
	Address     netip.Addr  `json:"address"`
	Column4     interface{} `json:"column_4"`
	IpAddressID pgtype.UUID `json:"ip_address_id"`
	MatchStatus string      `json:"match_status"`
	MatchCount  int32       `json:"match_count"`
}

func (q *Queries) CreateKubernetesServiceAddress(ctx context.Context, arg CreateKubernetesServiceAddressParams) error {
	_, err := q.db.Exec(ctx, createKubernetesServiceAddress,
		arg.ServiceID,
		arg.Kind,
		arg.Address,
		arg.Column4,
		arg.IpAddressID,
		arg.MatchStatus,
		arg.MatchCount,
	)
	return err
}

const createKubernetesServiceHostname = `-- name: CreateKubernetesServiceHostname :exec
INSERT INTO kubernetes_service_hostnames (service_id, kind, hostname)
VALUES ($1, $2, $3)
`

type CreateKubernetesServiceHostnameParams struct {
	ServiceID pgtype.UUID `json:"service_id"`
	Kind      string      `json:"kind"`
	Hostname  string      `json:"hostname"`
}

func (q *Queries) CreateKubernetesServiceHostname(ctx context.Context, arg CreateKubernetesServiceHostnameParams) error {
	_, err := q.db.Exec(ctx, createKubernetesServiceHostname, arg.ServiceID, arg.Kind, arg.Hostname)
	return err
}

const createKubernetesServicePort = `-- name: CreateKubernetesServicePort :exec
INSERT INTO kubernetes_service_ports (
    service_id, name, protocol, port, target_port, app_protocol, node_port
) VALUES ($1, NULLIF($2, ''), $3, $4, $5, NULLIF($6, ''), NULLIF($7, 0))
`

type CreateKubernetesServicePortParams struct {
	ServiceID  pgtype.UUID `json:"service_id"`
	Column2    interface{} `json:"column_2"`
	Protocol   string      `json:"protocol"`
	Port       int32       `json:"port"`
	TargetPort string      `json:"target_port"`
	Column6    interface{} `json:"column_6"`
	Column7    interface{} `json:"column_7"`
}

func (q *Queries) CreateKubernetesServicePort(ctx context.Context, arg CreateKubernetesServicePortParams) error {
	_, err := q.db.Exec(ctx, createKubernetesServicePort,
		arg.ServiceID,
		arg.Column2,
		arg.Protocol,
		arg.Port,
		arg.TargetPort,
		arg.Column6,
		arg.Column7,
	)
	return err
}

const deleteKubernetesServiceAddresses = `-- name: DeleteKubernetesServiceAddresses :exec
DELETE FROM kubernetes_service_addresses WHERE service_id = $1
`

func (q *Queries) DeleteKubernetesServiceAddresses(ctx context.Context, serviceID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteKubernetesServiceAddresses, serviceID)
	return err
}

const deleteKubernetesServiceHostnames = `-- name: DeleteKubernetesServiceHostnames :exec
DELETE FROM kubernetes_service_hostnames WHERE service_id = $1
`

func (q *Queries) DeleteKubernetesServiceHostnames(ctx context.Context, serviceID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteKubernetesServiceHostnames, serviceID)
	return err
}

const deleteKubernetesServicePorts = `-- name: DeleteKubernetesServicePorts :exec
DELETE FROM kubernetes_service_ports WHERE service_id = $1
`

func (q *Queries) DeleteKubernetesServicePorts(ctx context.Context, serviceID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteKubernetesServicePorts, serviceID)
	return err
}

const deleteStaleKubernetesServices = `-- name: DeleteStaleKubernetesServices :exec
DELETE FROM kubernetes_services
WHERE source_id = $1 AND active = false AND stale_at <= $2
`

type DeleteStaleKubernetesServicesParams struct {
	SourceID pgtype.UUID        `json:"source_id"`
	StaleAt  pgtype.Timestamptz `json:"stale_at"`
}

func (q *Queries) DeleteStaleKubernetesServices(ctx context.Context, arg DeleteStaleKubernetesServicesParams) error {
	_, err := q.db.Exec(ctx, deleteStaleKubernetesServices, arg.SourceID, arg.StaleAt)
	return err
}

const ensureKubernetesSource = `-- name: EnsureKubernetesSource :exec
INSERT INTO kubernetes_sources (
    source_key, name, site_id, cluster_domain, namespace_scope
) VALUES ($1, $2, $3, $4, $5::text[])
ON CONFLICT (source_key) DO NOTHING
`

type EnsureKubernetesSourceParams struct {
	SourceKey     string      `json:"source_key"`
	Name          string      `json:"name"`
	SiteID        pgtype.UUID `json:"site_id"`
	ClusterDomain string      `json:"cluster_domain"`
	Column5       []string    `json:"column_5"`
}

func (q *Queries) EnsureKubernetesSource(ctx context.Context, arg EnsureKubernetesSourceParams) error {
	_, err := q.db.Exec(ctx, ensureKubernetesSource,
		arg.SourceKey,
		arg.Name,
		arg.SiteID,
		arg.ClusterDomain,
		arg.Column5,
	)
	return err
}

const findIPCandidatesBySiteAndAddress = `-- name: FindIPCandidatesBySiteAndAddress :many
SELECT ip_addresses.id
FROM ip_addresses
JOIN subnets ON subnets.id = ip_addresses.subnet_id
WHERE subnets.site_id = $1 AND ip_addresses.ip = $2::inet
ORDER BY ip_addresses.id
`

type FindIPCandidatesBySiteAndAddressParams struct {
	SiteID  pgtype.UUID `json:"site_id"`
	Column2 netip.Addr  `json:"column_2"`
}

func (q *Queries) FindIPCandidatesBySiteAndAddress(ctx context.Context, arg FindIPCandidatesBySiteAndAddressParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, findIPCandidatesBySiteAndAddress, arg.SiteID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getKubernetesSourceByKey = `-- name: GetKubernetesSourceByKey :one
SELECT id, source_key, name, site_id, cluster_domain, namespace_scope, last_attempt_at, last_success_at, last_error, service_count, matched_count, unmatched_count, ambiguous_count, created_at, updated_at FROM kubernetes_sources WHERE source_key = $1
`

func (q *Queries) GetKubernetesSourceByKey(ctx context.Context, sourceKey string) (KubernetesSource, error) {
	row := q.db.QueryRow(ctx, getKubernetesSourceByKey, sourceKey)
	var i KubernetesSource
	err := row.Scan(
		&i.ID,
		&i.SourceKey,
		&i.Name,
		&i.SiteID,
		&i.ClusterDomain,
		&i.NamespaceScope,
		&i.LastAttemptAt,
		&i.LastSuccessAt,
		&i.LastError,
		&i.ServiceCount,
		&i.MatchedCount,
		&i.UnmatchedCount,
		&i.AmbiguousCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listKubernetesSourceStatuses = `-- name: ListKubernetesSourceStatuses :many
SELECT source_key, name, site_id, cluster_domain, namespace_scope,
       last_attempt_at, last_success_at, last_error,
       service_count, matched_count, unmatched_count, ambiguous_count
FROM kubernetes_sources
ORDER BY source_key
`

type ListKubernetesSourceStatusesRow struct {
	SourceKey      string             `json:"source_key"`
	Name           string             `json:"name"`
	SiteID         pgtype.UUID        `json:"site_id"`
	ClusterDomain  string             `json:"cluster_domain"`
	NamespaceScope []string           `json:"namespace_scope"`
	LastAttemptAt  pgtype.Timestamptz `json:"last_attempt_at"`
	LastSuccessAt  pgtype.Timestamptz `json:"last_success_at"`
	LastError      string             `json:"last_error"`
	ServiceCount   int32              `json:"service_count"`
	MatchedCount   int32              `json:"matched_count"`
	UnmatchedCount int32              `json:"unmatched_count"`
	AmbiguousCount int32              `json:"ambiguous_count"`
}

func (q *Queries) ListKubernetesSourceStatuses(ctx context.Context) ([]ListKubernetesSourceStatusesRow, error) {
	rows, err := q.db.Query(ctx, listKubernetesSourceStatuses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListKubernetesSourceStatusesRow
	for rows.Next() {
		var i ListKubernetesSourceStatusesRow
		if err := rows.Scan(
			&i.SourceKey,
			&i.Name,
			&i.SiteID,
			&i.ClusterDomain,
			&i.NamespaceScope,
			&i.LastAttemptAt,
			&i.LastSuccessAt,
			&i.LastError,
			&i.ServiceCount,
			&i.MatchedCount,
			&i.UnmatchedCount,
			&i.AmbiguousCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMatchedKubernetesServicesBySubnet = `-- name: ListMatchedKubernetesServicesBySubnet :many
SELECT a.ip_address_id,
       src.source_key,
       src.name AS source_name,
       svc.kubernetes_uid,
       svc.name,
       svc.namespace,
       svc.service_type,
       svc.dns_name,
       svc.observed_at,
       a.address,
       a.kind AS address_kind,
       port.name AS port_name,
       port.protocol,
       port.port,
       port.target_port,
       port.app_protocol,
       port.node_port
FROM kubernetes_service_addresses a
JOIN kubernetes_services svc ON svc.id = a.service_id
JOIN kubernetes_sources src ON src.id = svc.source_id
JOIN ip_addresses ip ON ip.id = a.ip_address_id
JOIN subnets subnet ON subnet.id = ip.subnet_id
LEFT JOIN kubernetes_service_ports port ON port.service_id = svc.id
WHERE ip.subnet_id = $1
  AND subnet.site_id = src.site_id
  AND svc.active = true
  AND a.match_status = 'matched'
ORDER BY a.ip_address_id, src.source_key, svc.namespace, svc.name, svc.kubernetes_uid,
         a.kind, port.port, port.protocol, port.name
`

type ListMatchedKubernetesServicesBySubnetRow struct {
	IpAddressID   pgtype.UUID        `json:"ip_address_id"`
	SourceKey     string             `json:"source_key"`
	SourceName    string             `json:"source_name"`
	KubernetesUid string             `json:"kubernetes_uid"`
	Name          string             `json:"name"`
	Namespace     string             `json:"namespace"`
	ServiceType   string             `json:"service_type"`
	DnsName       string             `json:"dns_name"`
	ObservedAt    pgtype.Timestamptz `json:"observed_at"`
	Address       netip.Addr         `json:"address"`
	AddressKind   string             `json:"address_kind"`
	PortName      pgtype.Text        `json:"port_name"`
	Protocol      pgtype.Text        `json:"protocol"`
	Port          pgtype.Int4        `json:"port"`
	TargetPort    pgtype.Text        `json:"target_port"`
	AppProtocol   pgtype.Text        `json:"app_protocol"`
	NodePort      pgtype.Int4        `json:"node_port"`
}

func (q *Queries) ListMatchedKubernetesServicesBySubnet(ctx context.Context, subnetID int64) ([]ListMatchedKubernetesServicesBySubnetRow, error) {
	rows, err := q.db.Query(ctx, listMatchedKubernetesServicesBySubnet, subnetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMatchedKubernetesServicesBySubnetRow
	for rows.Next() {
		var i ListMatchedKubernetesServicesBySubnetRow
		if err := rows.Scan(
			&i.IpAddressID,
			&i.SourceKey,
			&i.SourceName,
			&i.KubernetesUid,
			&i.Name,
			&i.Namespace,
			&i.ServiceType,
			&i.DnsName,
			&i.ObservedAt,
			&i.Address,
			&i.AddressKind,
			&i.PortName,
			&i.Protocol,
			&i.Port,
			&i.TargetPort,
			&i.AppProtocol,
			&i.NodePort,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMissingKubernetesServicesInactive = `-- name: MarkMissingKubernetesServicesInactive :exec
UPDATE kubernetes_services
SET active = false, stale_at = $3, updated_at = now()
WHERE source_id = $1
  AND active = true
  AND NOT (kubernetes_uid = ANY($2::text[]))
`

type MarkMissingKubernetesServicesInactiveParams struct {
	SourceID pgtype.UUID        `json:"source_id"`
	Column2  []string           `json:"column_2"`
	StaleAt  pgtype.Timestamptz `json:"stale_at"`
}

func (q *Queries) MarkMissingKubernetesServicesInactive(ctx context.Context, arg MarkMissingKubernetesServicesInactiveParams) error {
	_, err := q.db.Exec(ctx, markMissingKubernetesServicesInactive, arg.SourceID, arg.Column2, arg.StaleAt)
	return err
}

const recordKubernetesSourceFailure = `-- name: RecordKubernetesSourceFailure :exec
UPDATE kubernetes_sources
SET last_attempt_at = $2, last_error = $3, updated_at = now()
WHERE id = $1
`

type RecordKubernetesSourceFailureParams struct {
	ID            pgtype.UUID        `json:"id"`
	LastAttemptAt pgtype.Timestamptz `json:"last_attempt_at"`
	LastError     string             `json:"last_error"`
}

func (q *Queries) RecordKubernetesSourceFailure(ctx context.Context, arg RecordKubernetesSourceFailureParams) error {
	_, err := q.db.Exec(ctx, recordKubernetesSourceFailure, arg.ID, arg.LastAttemptAt, arg.LastError)
	return err
}

const recordKubernetesSourceSuccess = `-- name: RecordKubernetesSourceSuccess :exec
UPDATE kubernetes_sources
SET last_attempt_at = $2,
    last_success_at = $2,
    last_error = '',
    service_count = $3,
    matched_count = $4,
    unmatched_count = $5,
    ambiguous_count = $6,
    updated_at = now()
WHERE id = $1
`

type RecordKubernetesSourceSuccessParams struct {
	ID             pgtype.UUID        `json:"id"`
	LastAttemptAt  pgtype.Timestamptz `json:"last_attempt_at"`
	ServiceCount   int32              `json:"service_count"`
	MatchedCount   int32              `json:"matched_count"`
	UnmatchedCount int32              `json:"unmatched_count"`
	AmbiguousCount int32              `json:"ambiguous_count"`
}

func (q *Queries) RecordKubernetesSourceSuccess(ctx context.Context, arg RecordKubernetesSourceSuccessParams) error {
	_, err := q.db.Exec(ctx, recordKubernetesSourceSuccess,
		arg.ID,
		arg.LastAttemptAt,
		arg.ServiceCount,
		arg.MatchedCount,
		arg.UnmatchedCount,
		arg.AmbiguousCount,
	)
	return err
}

const tryKubernetesSourceLock = `-- name: TryKubernetesSourceLock :one
SELECT pg_try_advisory_xact_lock(hashtextextended($1, 0))
`

func (q *Queries) TryKubernetesSourceLock(ctx context.Context, hashtextextended string) (bool, error) {
	row := q.db.QueryRow(ctx, tryKubernetesSourceLock, hashtextextended)
	var pg_try_advisory_xact_lock bool
	err := row.Scan(&pg_try_advisory_xact_lock)
	return pg_try_advisory_xact_lock, err
}

const upsertKubernetesService = `-- name: UpsertKubernetesService :one
INSERT INTO kubernetes_services (
    source_id, kubernetes_uid, namespace, name, service_type,
    resource_version, external_name, dns_name, observed_at, active, stale_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, true, NULL)
ON CONFLICT (source_id, kubernetes_uid) DO UPDATE SET
    namespace = EXCLUDED.namespace,
    name = EXCLUDED.name,
    service_type = EXCLUDED.service_type,
    resource_version = EXCLUDED.resource_version,
    external_name = EXCLUDED.external_name,
    dns_name = EXCLUDED.dns_name,
    observed_at = EXCLUDED.observed_at,
    active = true,
    stale_at = NULL,
    updated_at = now()
RETURNING id, source_id, kubernetes_uid, namespace, name, service_type, resource_version, external_name, dns_name, observed_at, active, stale_at, created_at, updated_at
`

type UpsertKubernetesServiceParams struct {
	SourceID        pgtype.UUID        `json:"source_id"`
	KubernetesUid   string             `json:"kubernetes_uid"`
	Namespace       string             `json:"namespace"`
	Name            string             `json:"name"`
	ServiceType     string             `json:"service_type"`
	ResourceVersion string             `json:"resource_version"`
	ExternalName    string             `json:"external_name"`
	DnsName         string             `json:"dns_name"`
	ObservedAt      pgtype.Timestamptz `json:"observed_at"`
}

func (q *Queries) UpsertKubernetesService(ctx context.Context, arg UpsertKubernetesServiceParams) (KubernetesService, error) {
	row := q.db.QueryRow(ctx, upsertKubernetesService,
		arg.SourceID,
		arg.KubernetesUid,
		arg.Namespace,
		arg.Name,
		arg.ServiceType,
		arg.ResourceVersion,
		arg.ExternalName,
		arg.DnsName,
		arg.ObservedAt,
	)
	var i KubernetesService
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.KubernetesUid,
		&i.Namespace,
		&i.Name,
		&i.ServiceType,
		&i.ResourceVersion,
		&i.ExternalName,
		&i.DnsName,
		&i.ObservedAt,
		&i.Active,
		&i.StaleAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertKubernetesSource = `-- name: UpsertKubernetesSource :one
INSERT INTO kubernetes_sources (
    source_key, name, site_id, cluster_domain, namespace_scope, updated_at
) VALUES ($1, $2, $3, $4, $5::text[], now())
ON CONFLICT (source_key) DO UPDATE SET
    name = EXCLUDED.name,
    site_id = EXCLUDED.site_id,
    cluster_domain = EXCLUDED.cluster_domain,
    namespace_scope = EXCLUDED.namespace_scope,
    updated_at = now()
RETURNING id, source_key, name, site_id, cluster_domain, namespace_scope, last_attempt_at, last_success_at, last_error, service_count, matched_count, unmatched_count, ambiguous_count, created_at, updated_at
`

type UpsertKubernetesSourceParams struct {
	SourceKey     string      `json:"source_key"`
	Name          string      `json:"name"`
	SiteID        pgtype.UUID `json:"site_id"`
	ClusterDomain string      `json:"cluster_domain"`
	Column5       []string    `json:"column_5"`
}

func (q *Queries) UpsertKubernetesSource(ctx context.Context, arg UpsertKubernetesSourceParams) (KubernetesSource, error) {
	row := q.db.QueryRow(ctx, upsertKubernetesSource,
		arg.SourceKey,
		arg.Name,
		arg.SiteID,
		arg.ClusterDomain,
		arg.Column5,
	)
	var i KubernetesSource
	err := row.Scan(
		&i.ID,
		&i.SourceKey,
		&i.Name,
		&i.SiteID,
		&i.ClusterDomain,
		&i.NamespaceScope,
		&i.LastAttemptAt,
		&i.LastSuccessAt,
		&i.LastError,
		&i.ServiceCount,
		&i.MatchedCount,
		&i.UnmatchedCount,
		&i.AmbiguousCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
