// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reporting.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const captureDueSubnetUsageSnapshots = `-- name: CaptureDueSubnetUsageSnapshots :one
WITH due AS (
    UPDATE reporting_settings
    SET last_snapshot_at = NOW()
    WHERE singleton = TRUE
      AND (
          last_snapshot_at IS NULL
          OR last_snapshot_at <= NOW() - CASE cadence
              WHEN 'hourly' THEN INTERVAL '1 hour'
              WHEN 'daily' THEN INTERVAL '1 day'
              WHEN 'weekly' THEN INTERVAL '1 week'
          END
      )
    RETURNING last_snapshot_at
), inserted AS (
    INSERT INTO subnet_usage_snapshots (subnet_id, captured_at, used_ips, total_ips)
    SELECT subnets.id,
           due.last_snapshot_at,
           COUNT(ip_addresses.id),
           GREATEST(
               COUNT(ip_addresses.id),
               POWER(2::numeric, (32 - masklen(subnets.cidr))::numeric)::bigint
           )
    FROM subnets
    CROSS JOIN due
    LEFT JOIN ip_addresses ON ip_addresses.subnet_id = subnets.id
    WHERE family(subnets.cidr) = 4
    GROUP BY subnets.id, subnets.cidr, due.last_snapshot_at
    RETURNING 1
)
SELECT COUNT(*) FROM inserted
`

func (q *Queries) CaptureDueSubnetUsageSnapshots(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, captureDueSubnetUsageSnapshots)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteExpiredSubnetUsageSnapshots = `-- name: DeleteExpiredSubnetUsageSnapshots :execrows
DELETE FROM subnet_usage_snapshots
WHERE captured_at < NOW() - make_interval(days => (
    SELECT retention_days FROM reporting_settings WHERE singleton = TRUE
))
`

func (q *Queries) DeleteExpiredSubnetUsageSnapshots(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSubnetUsageSnapshots)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getReportingSettings = `-- name: GetReportingSettings :one
SELECT cadence, retention_days, last_snapshot_at
FROM reporting_settings
WHERE singleton = TRUE
`

type GetReportingSettingsRow struct {
	Cadence        string             `json:"cadence"`
	RetentionDays  int32              `json:"retention_days"`
	LastSnapshotAt pgtype.Timestamptz `json:"last_snapshot_at"`
}

func (q *Queries) GetReportingSettings(ctx context.Context) (GetReportingSettingsRow, error) {
	row := q.db.QueryRow(ctx, getReportingSettings)
	var i GetReportingSettingsRow
	err := row.Scan(&i.Cadence, &i.RetentionDays, &i.LastSnapshotAt)
	return i, err
}

const listSubnetUsageSnapshots = `-- name: ListSubnetUsageSnapshots :many
SELECT subnet_id, captured_at, used_ips, total_ips
FROM subnet_usage_snapshots
WHERE subnet_id = $1
  AND captured_at >= $2
  AND captured_at <= $3
ORDER BY captured_at
`

type ListSubnetUsageSnapshotsParams struct {
	SubnetID     int64              `json:"subnet_id"`
	CapturedAt   pgtype.Timestamptz `json:"captured_at"`
	CapturedAt_2 pgtype.Timestamptz `json:"captured_at_2"`
}

func (q *Queries) ListSubnetUsageSnapshots(ctx context.Context, arg ListSubnetUsageSnapshotsParams) ([]SubnetUsageSnapshot, error) {
	rows, err := q.db.Query(ctx, listSubnetUsageSnapshots, arg.SubnetID, arg.CapturedAt, arg.CapturedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SubnetUsageSnapshot
	for rows.Next() {
		var i SubnetUsageSnapshot
		if err := rows.Scan(
			&i.SubnetID,
			&i.CapturedAt,
			&i.UsedIps,
			&i.TotalIps,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReportingSettings = `-- name: UpdateReportingSettings :one
UPDATE reporting_settings
SET cadence = $1, retention_days = $2
WHERE singleton = TRUE
RETURNING cadence, retention_days, last_snapshot_at
`

type UpdateReportingSettingsParams struct {
	Cadence       string `json:"cadence"`
	RetentionDays int32  `json:"retention_days"`
}

type UpdateReportingSettingsRow struct {
	Cadence        string             `json:"cadence"`
	RetentionDays  int32              `json:"retention_days"`
	LastSnapshotAt pgtype.Timestamptz `json:"last_snapshot_at"`
}

func (q *Queries) UpdateReportingSettings(ctx context.Context, arg UpdateReportingSettingsParams) (UpdateReportingSettingsRow, error) {
	row := q.db.QueryRow(ctx, updateReportingSettings, arg.Cadence, arg.RetentionDays)
	var i UpdateReportingSettingsRow
	err := row.Scan(&i.Cadence, &i.RetentionDays, &i.LastSnapshotAt)
	return i, err
}
