// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sites.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSite = `-- name: CreateSite :one
INSERT INTO sites (id, name, description)
VALUES ($1, $2, $3)
RETURNING id, name , description, created_at, updated_at
`

type CreateSiteParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
}

func (q *Queries) CreateSite(ctx context.Context, arg CreateSiteParams) (Site, error) {
	row := q.db.QueryRow(ctx, createSite, arg.ID, arg.Name, arg.Description)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSiteByID = `-- name: DeleteSiteByID :one
WITH deleted_rows AS (
    DELETE FROM sites
        WHERE id = $1
        RETURNING id, name, description, created_at, updated_at
)
SELECT count(*) FROM deleted_rows
`

func (q *Queries) DeleteSiteByID(ctx context.Context, id pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, deleteSiteByID, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getSiteByID = `-- name: GetSiteByID :one
SELECT id, name, description, created_at, updated_at
FROM sites
WHERE id = $1
`

func (q *Queries) GetSiteByID(ctx context.Context, id pgtype.UUID) (Site, error) {
	row := q.db.QueryRow(ctx, getSiteByID, id)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSites = `-- name: ListSites :many
SELECT id, name, description, created_at, updated_at
FROM sites
ORDER BY id
`

func (q *Queries) ListSites(ctx context.Context) ([]Site, error) {
	rows, err := q.db.Query(ctx, listSites)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Site
	for rows.Next() {
		var i Site
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const perSubnetStatistics = `-- name: PerSubnetStatistics :many
SELECT sites.id, subnets.id sub_id, subnets.cidr as cidr, COUNT(ip_addresses.id) as used_ips
FROM sites
LEFT JOIN subnets
ON sites.id = subnets.site_id
LEFT JOIN ip_addresses
ON subnets.id = ip_addresses.subnet_id
GROUP BY sites.id, subnets.id, subnets.cidr
`

type PerSubnetStatisticsRow struct {
	ID      pgtype.UUID   `json:"id"`
	SubID   pgtype.Int8   `json:"sub_id"`
	Cidr    *netip.Prefix `json:"cidr"`
	UsedIps int64         `json:"used_ips"`
}

func (q *Queries) PerSubnetStatistics(ctx context.Context) ([]PerSubnetStatisticsRow, error) {
	rows, err := q.db.Query(ctx, perSubnetStatistics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PerSubnetStatisticsRow
	for rows.Next() {
		var i PerSubnetStatisticsRow
		if err := rows.Scan(
			&i.ID,
			&i.SubID,
			&i.Cidr,
			&i.UsedIps,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSite = `-- name: UpdateSite :one
UPDATE sites
SET name = $2, description = $3, updated_at = now() AT TIME ZONE 'UTC'
WHERE id = $1
RETURNING id, name, description, created_at, updated_at
`

type UpdateSiteParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
}

func (q *Queries) UpdateSite(ctx context.Context, arg UpdateSiteParams) (Site, error) {
	row := q.db.QueryRow(ctx, updateSite, arg.ID, arg.Name, arg.Description)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
