// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subnets.sql

package db

import (
	"context"
)

const createSubnet = `-- name: CreateSubnet :one
INSERT INTO subnets (cidr, description)
VALUES ($1, $2)
RETURNING id, cidr, description, created_at
`

type CreateSubnetParams struct {
	Cidr        string `json:"cidr"`
	Description string `json:"description"`
}

func (q *Queries) CreateSubnet(ctx context.Context, arg CreateSubnetParams) (Subnet, error) {
	row := q.db.QueryRow(ctx, createSubnet, arg.Cidr, arg.Description)
	var i Subnet
	err := row.Scan(
		&i.ID,
		&i.Cidr,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const listSubnets = `-- name: ListSubnets :many
SELECT id, cidr, description, created_at
FROM subnets
ORDER BY id
`

func (q *Queries) ListSubnets(ctx context.Context) ([]Subnet, error) {
	rows, err := q.db.Query(ctx, listSubnets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subnet
	for rows.Next() {
		var i Subnet
		if err := rows.Scan(
			&i.ID,
			&i.Cidr,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
