// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subnets.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignSubnetSite = `-- name: AssignSubnetSite :one
UPDATE subnets
SET site_id = $2, updated_at = now() AT TIME ZONE 'UTC'
WHERE id = $1
RETURNING id, cidr, description, created_at, updated_at, site_id
`

type AssignSubnetSiteParams struct {
	ID     int64       `json:"id"`
	SiteID pgtype.UUID `json:"site_id"`
}

func (q *Queries) AssignSubnetSite(ctx context.Context, arg AssignSubnetSiteParams) (Subnet, error) {
	row := q.db.QueryRow(ctx, assignSubnetSite, arg.ID, arg.SiteID)
	var i Subnet
	err := row.Scan(
		&i.ID,
		&i.Cidr,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SiteID,
	)
	return i, err
}

const createSubnet = `-- name: CreateSubnet :one
INSERT INTO subnets (cidr, site_id, description)
VALUES ($1, $2, $3)
RETURNING id, cidr, description, created_at, updated_at, site_id
`

type CreateSubnetParams struct {
	Cidr        netip.Prefix `json:"cidr"`
	SiteID      pgtype.UUID  `json:"site_id"`
	Description string       `json:"description"`
}

func (q *Queries) CreateSubnet(ctx context.Context, arg CreateSubnetParams) (Subnet, error) {
	row := q.db.QueryRow(ctx, createSubnet, arg.Cidr, arg.SiteID, arg.Description)
	var i Subnet
	err := row.Scan(
		&i.ID,
		&i.Cidr,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SiteID,
	)
	return i, err
}

const deleteSubnetByID = `-- name: DeleteSubnetByID :one
WITH deleted_rows AS (
    DELETE FROM subnets
    WHERE id = $1
    RETURNING id, cidr, description, created_at, updated_at, site_id
)
SELECT count(*) FROM deleted_rows
`

func (q *Queries) DeleteSubnetByID(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, deleteSubnetByID, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getSubnetByID = `-- name: GetSubnetByID :one
SELECT subnets.id, subnets.cidr, subnets.description, subnets.created_at, subnets.updated_at, subnets.site_id,
       (SELECT COUNT(*) FROM ip_addresses WHERE subnet_id = subnets.id) AS used_ips
FROM subnets
WHERE subnets.id = $1
`

type GetSubnetByIDRow struct {
	ID          int64              `json:"id"`
	Cidr        netip.Prefix       `json:"cidr"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	SiteID      pgtype.UUID        `json:"site_id"`
	UsedIps     int64              `json:"used_ips"`
}

func (q *Queries) GetSubnetByID(ctx context.Context, id int64) (GetSubnetByIDRow, error) {
	row := q.db.QueryRow(ctx, getSubnetByID, id)
	var i GetSubnetByIDRow
	err := row.Scan(
		&i.ID,
		&i.Cidr,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SiteID,
		&i.UsedIps,
	)
	return i, err
}

const listSubnets = `-- name: ListSubnets :many
SELECT subnets.id, subnets.cidr, subnets.description, subnets.created_at, subnets.updated_at, subnets.site_id,
       (SELECT COUNT(*) FROM ip_addresses WHERE subnet_id = subnets.id) AS used_ips
FROM subnets
ORDER BY subnets.id
`

type ListSubnetsRow struct {
	ID          int64              `json:"id"`
	Cidr        netip.Prefix       `json:"cidr"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	SiteID      pgtype.UUID        `json:"site_id"`
	UsedIps     int64              `json:"used_ips"`
}

func (q *Queries) ListSubnets(ctx context.Context) ([]ListSubnetsRow, error) {
	rows, err := q.db.Query(ctx, listSubnets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSubnetsRow
	for rows.Next() {
		var i ListSubnetsRow
		if err := rows.Scan(
			&i.ID,
			&i.Cidr,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SiteID,
			&i.UsedIps,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSubnet = `-- name: UpdateSubnet :one
UPDATE subnets
SET cidr = $2, site_id = $3, description = $4, updated_at = now() AT TIME ZONE 'UTC'
WHERE id = $1
RETURNING id, cidr, description, created_at, updated_at, site_id
`

type UpdateSubnetParams struct {
	ID          int64        `json:"id"`
	Cidr        netip.Prefix `json:"cidr"`
	SiteID      pgtype.UUID  `json:"site_id"`
	Description string       `json:"description"`
}

func (q *Queries) UpdateSubnet(ctx context.Context, arg UpdateSubnetParams) (Subnet, error) {
	row := q.db.QueryRow(ctx, updateSubnet,
		arg.ID,
		arg.Cidr,
		arg.SiteID,
		arg.Description,
	)
	var i Subnet
	err := row.Scan(
		&i.ID,
		&i.Cidr,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SiteID,
	)
	return i, err
}
