import type { KubernetesServiceSummary, SiteStatistics, Subnet, SubnetUsage } from "../types";

type Props = { subnets: Subnet[]; sites: SiteStatistics[]; usage: Record<number, SubnetUsage>; summaries: Record<number, KubernetesServiceSummary>; loading: boolean; error: string | null; canCreate: boolean; onSelectSubnet: (subnet: Subnet) => void; onAddSubnet: () => void };
const format = (value: number) => value.toLocaleString();
const serviceSummary = (summary?: KubernetesServiceSummary) => !summary ? "Loading Services…" : summary.state === "unavailable" ? "Kubernetes discovery unavailable" : summary.count ? `${summary.count} Service${summary.count === 1 ? "" : "s"} observed` : "No Services observed";

export default function DashboardView({ subnets, sites, usage, summaries, loading, error, canCreate, onSelectSubnet, onAddSubnet }: Props) {
	const total = subnets.reduce((sum, subnet) => sum + (usage[subnet.id]?.total ?? 0), 0);
	const used = subnets.reduce((sum, subnet) => sum + (usage[subnet.id]?.used ?? 0), 0);
	return <main className="content"><div className="page-heading"><div><p className="eyebrow">Overview</p><h1>Dashboard</h1><p className="muted">A quick view of your network inventory and capacity.</p></div>{canCreate ? <button className="primary" onClick={onAddSubnet}>+ Add subnet</button> : null}</div>{error ? <div className="error">{error}</div> : null}
		<section className="stats-grid"><div className="stat-card"><span className="stat-card__label">Total subnets</span><strong>{format(subnets.length)}</strong><span className="muted">CIDR networks</span></div><div className="stat-card"><span className="stat-card__label">Allocated IPs</span><strong>{format(used)}</strong><span className="muted">of {format(total)} total capacity</span></div><div className="stat-card"><span className="stat-card__label">Available IPs</span><strong>{format(Math.max(total - used, 0))}</strong><span className="muted">across all subnets</span></div><div className="stat-card"><span className="stat-card__label">Sites</span><strong>{format(sites.length)}</strong><span className="muted">managed locations</span></div></section>
		<div className="dashboard-grid"><section className="card"><div className="section-heading"><div><h2>Subnet usage</h2><p className="muted">Select a subnet to manage its IP addresses.</p></div></div>{loading ? <p className="muted">Loading usage…</p> : subnets.length === 0 ? <div className="empty-state empty-state--compact"><p className="muted">No subnets yet.</p><button className="secondary" onClick={onAddSubnet}>Add a subnet</button></div> : <div className="dashboard-subnet-list">{subnets.map((subnet) => { const item = usage[subnet.id] ?? { used: 0, total: 0 }; const site = sites.find((candidate) => candidate.id === subnet.site_id); return <a className="dashboard-subnet" href={`/subnets/${subnet.id}`} key={subnet.id} onClick={(event) => { event.preventDefault(); onSelectSubnet(subnet); }}><div><strong className="mono">{subnet.cidr}</strong><span className="muted">{site?.name || "Unassigned"} · {subnet.description || "No description"}</span></div><div className="dashboard-subnet__usage"><strong>{format(item.used)} / {format(item.total)}</strong><span className="muted">{serviceSummary(summaries[subnet.id])}</span><div className="usage-bar"><span style={{ width: `${item.total ? Math.min(item.used / item.total * 100, 100) : 0}%` }} /></div></div></a>; })}</div>}</section>
			<section className="card"><div className="section-heading"><div><h2>Site usage</h2><p className="muted">Capacity grouped by location.</p></div></div><div className="site-summary-list">{sites.length === 0 ? <p className="muted">No sites yet.</p> : sites.map((site) => <div className="site-summary" key={site.id}><div><strong>{site.name}</strong><span className="muted">{site.subnet_count} subnets</span></div><div className="site-summary__numbers"><strong>{format(site.used_ip_count)} / {format(site.total_ip_count)}</strong><span className="muted">{format(site.free_ip_count)} free</span></div></div>)}</div></section>
		</div>
	</main>;
}
