import { FormEvent, useState } from "react";
import type { SiteStatistics } from "../types";

type Props = { sites: SiteStatistics[]; loading: boolean; error: string | null; onSave: (data: { id?: string; name: string; description: string }) => Promise<void>; onDelete: (site: SiteStatistics) => Promise<void>; onImport: () => void };
export default function SitesView({ sites, loading, error, onSave, onDelete, onImport }: Props) {
	const [formOpen, setFormOpen] = useState(false); const [editing, setEditing] = useState<SiteStatistics | null>(null); const [name, setName] = useState(""); const [description, setDescription] = useState(""); const [saving, setSaving] = useState(false); const [formError, setFormError] = useState<string | null>(null);
	const open = (site?: SiteStatistics) => { setEditing(site ?? null); setName(site?.name ?? ""); setDescription(site?.description ?? ""); setFormError(null); setFormOpen(true); };
	const submit = async (event: FormEvent) => { event.preventDefault(); if (!name.trim()) { setFormError("Name is required"); return; } setSaving(true); setFormError(null); try { await onSave({ id: editing?.id, name, description }); setFormOpen(false); setEditing(null); } catch (err) { setFormError(err instanceof Error ? err.message : "Unable to save site"); } finally { setSaving(false); } };
		return <main className="content"><div className="page-heading"><div><p className="eyebrow">Organization</p><h1>Sites</h1><p className="muted">Manage locations and review their network capacity.</p></div><div className="button-group"><button className="secondary" onClick={onImport}>Import CSV</button><button className="primary" onClick={() => open()}>+ Add site</button></div></div><section className="card card--table">{loading ? <p className="muted">Loading sites…</p> : error ? <div className="error">{error}</div> : <table className="table"><thead><tr><th>Site</th><th>Subnets</th><th>IP usage</th><th>Available</th><th>Updated</th><th /></tr></thead><tbody>{sites.length === 0 ? <tr><td colSpan={6} className="muted">No sites yet.</td></tr> : sites.map((site) => <tr key={site.id}><td><strong>{site.name}</strong><div className="muted">{site.description || "No description"}</div></td><td>{site.subnet_count}</td><td>{site.used_ip_count.toLocaleString()} / {site.total_ip_count.toLocaleString()}</td><td>{site.free_ip_count.toLocaleString()}</td><td className="muted">{new Date(site.updated_at).toLocaleDateString()}</td><td className="actions"><button className="secondary" onClick={() => open(site)}>Edit</button><button className="secondary danger" onClick={() => void onDelete(site)}>Delete</button></td></tr>)}</tbody></table>}</section>{formOpen ? <div className="modal"><div className="modal__backdrop" onClick={() => setFormOpen(false)} /><form className="modal__content" onSubmit={submit}><p className="eyebrow">{editing ? "Edit site" : "New site"}</p><h2 className="title">{editing ? editing.name : "Create a site"}</h2><label className="field"><span>Name</span><input value={name} onChange={(event) => setName(event.target.value)} autoFocus /></label><label className="field"><span>Description</span><input value={description} onChange={(event) => setDescription(event.target.value)} placeholder="Primary office" /></label>{formError ? <div className="error">{formError}</div> : null}<div className="modal__actions"><button type="button" className="secondary" onClick={() => setFormOpen(false)}>Cancel</button><button className="primary" disabled={saving}>{saving ? "Saving…" : "Save site"}</button></div></form></div> : null}</main>;
}
