import { memo, useEffect, useMemo, useState } from "react";
import { api, type Requester } from "../api";
import type { IPAddress, SiteStatistics, Subnet } from "../types";

const WINDOW = 256;
function parseCidr(cidr: string) { const [address, maskText] = cidr.split("/"); const mask = Number(maskText); const octets = address?.split(".").map(Number); if (!address || !Number.isInteger(mask) || mask < 0 || mask > 32 || !octets || octets.length !== 4 || octets.some((part) => !Number.isInteger(part) || part < 0 || part > 255)) return null; return { network: ((((octets[0] << 24) | (octets[1] << 16) | (octets[2] << 8) | octets[3]) >>> 0) & (mask === 0 ? 0 : (0xffffffff << (32 - mask)) >>> 0)) >>> 0, count: mask === 32 ? 1 : 2 ** (32 - mask) }; }
const ip = (value: number) => `${value >>> 24 & 255}.${value >>> 16 & 255}.${value >>> 8 & 255}.${value & 255}`;
const IpRow = memo(({ address, record, saving, onSave }: { address: string; record?: IPAddress; saving: boolean; onSave: (address: string, hostname: string) => void }) => { const [draft, setDraft] = useState(record?.hostname ?? ""); useEffect(() => setDraft(record?.hostname ?? ""), [record?.hostname]); return <tr><td className="mono">{address}</td><td><input value={draft} onChange={(event) => setDraft(event.target.value)} placeholder="(unset)" /></td><td className="muted">{record?.updated_at ? new Date(record.updated_at).toLocaleString() : ""}</td><td><button className="secondary" disabled={saving} onClick={() => onSave(address, draft)}>{saving ? "Saving…" : "Save"}</button></td></tr>; }, (a, b) => a.address === b.address && a.record?.id === b.record?.id && a.record?.hostname === b.record?.hostname && a.record?.updated_at === b.record?.updated_at && a.saving === b.saving);

type Props = { subnet: Subnet; site?: SiteStatistics; requester: Requester; onBack: () => void; onRefreshUsage: () => void };
export default function SubnetDetailView({ subnet, site, requester, onBack, onRefreshUsage }: Props) {
	const [records, setRecords] = useState<IPAddress[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState<string | null>(null); const [windowStart, setWindowStart] = useState(0);
	useEffect(() => { setLoading(true); void api.ips(requester, subnet.id).then(setRecords).catch((err) => setError(err instanceof Error ? err.message : "Unable to load IPs")).finally(() => setLoading(false)); }, [requester, subnet.id]);
	const parsed = useMemo(() => parseCidr(subnet.cidr), [subnet.cidr]); const max = parsed && parsed.count > WINDOW ? Math.floor((parsed.count - 1) / WINDOW) * WINDOW : 0; const start = Math.min(windowStart, max); const end = parsed ? Math.min(start + WINDOW, parsed.count) : 0; const addresses = useMemo(() => parsed ? Array.from({ length: end - start }, (_, index) => ip((parsed.network + start + index) >>> 0)) : [], [parsed, start, end]); const map = useMemo(() => new Map(records.map((record) => [record.ip, record])), [records]);
		const save = async (address: string, hostname: string) => { const existing = map.get(address); setSaving(address); try { if (existing && !hostname.trim()) { const response = await api.deleteIp(requester, subnet.id, existing.id); if (!response.ok) throw new Error("Unable to clear IP"); setRecords((current) => current.filter((record) => record.id !== existing.id)); } else { const saved = await api.saveIp(requester, subnet.id, existing, address, hostname); setRecords((current) => [saved, ...current.filter((record) => record.ip !== saved.ip)]); } onRefreshUsage(); } catch (err) { setError(err instanceof Error ? err.message : "Unable to save IP"); } finally { setSaving(null); } };
	return <main className="content"><button className="back-link" onClick={onBack}>← Back to subnets</button><div className="page-heading"><div><p className="eyebrow">Subnet detail</p><h1 className="mono">{subnet.cidr}</h1><p className="muted">{site ? `Owned by ${site.name}` : "Unassigned site"} · {subnet.description || "No description"}</p></div><div className="detail-count"><strong>{parsed?.count.toLocaleString() ?? "—"}</strong><span className="muted">total addresses</span></div></div>{error ? <div className="error">{error}</div> : null}<section className="card card--table">{loading ? <p className="muted">Loading IPs…</p> : !parsed ? <div className="error">Cannot render IPs for this CIDR.</div> : <><div className="table-toolbar"><span className="muted">Showing {start + 1}–{end} of {parsed.count.toLocaleString()}</span>{max ? <div className="button-group"><button className="secondary" onClick={() => setWindowStart((value) => Math.max(value - WINDOW, 0))} disabled={!start}>Previous</button><button className="secondary" onClick={() => setWindowStart((value) => Math.min(value + WINDOW, max))} disabled={start >= max}>Next</button></div> : null}</div><table className="table"><thead><tr><th>IP address</th><th>Hostname</th><th>Updated</th><th /></tr></thead><tbody>{addresses.map((address) => <IpRow key={address} address={address} record={map.get(address)} saving={saving === address} onSave={(value, hostname) => void save(value, hostname)} />)}</tbody></table></>}</section></main>;
}
