import { useState } from "react";
import type { SiteStatistics, Subnet } from "../types";

type Props = { subnets: Subnet[]; sites: SiteStatistics[]; loading: boolean; error: string | null; canCreate: boolean; canEdit: boolean; canDelete: boolean; onSelect: (subnet: Subnet) => void; onSave: (data: Partial<Subnet> & Pick<Subnet, "cidr" | "description">) => Promise<void>; onDelete: (subnet: Subnet) => Promise<void> };
export default function SubnetsView({ subnets, sites, loading, error, canCreate, canEdit, canDelete, onSelect, onSave, onDelete }: Props) {
	const [formOpen, setFormOpen] = useState(false); const [editing, setEditing] = useState<Subnet | null>(null); const [cidr, setCidr] = useState(""); const [description, setDescription] = useState(""); const [siteId, setSiteId] = useState(""); const [saving, setSaving] = useState(false); const [formError, setFormError] = useState<string | null>(null);
	const open = (subnet?: Subnet) => { setEditing(subnet ?? null); setCidr(subnet?.cidr ?? ""); setDescription(subnet?.description ?? ""); setSiteId(subnet?.site_id ?? ""); setFormError(null); setFormOpen(true); };
	const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!cidr.trim()) { setFormError("CIDR is required"); return; } if (!siteId) { setFormError("Site is required by the backend"); return; } setSaving(true); try { await onSave({ id: editing?.id, cidr, description, site_id: siteId }); setFormOpen(false); } catch (err) { setFormError(err instanceof Error ? err.message : "Unable to save subnet"); } finally { setSaving(false); } };
	return <main className="content"><div className="page-heading"><div><p className="eyebrow">Network inventory</p><h1>Subnets</h1><p className="muted">Manage CIDR networks and their site ownership.</p></div>{canCreate ? <button className="primary" onClick={() => open()}>+ Add subnet</button> : null}</div><section className="card card--table">{loading ? <p className="muted">Loading subnets…</p> : error ? <div className="error">{error}</div> : <table className="table"><thead><tr><th>CIDR</th><th>Site</th><th>Description</th><th>Updated</th>{canEdit || canDelete ? <th /> : null}</tr></thead><tbody>{subnets.length === 0 ? <tr><td colSpan={canEdit || canDelete ? 5 : 4} className="muted">No subnets yet.</td></tr> : subnets.map((subnet) => <tr className="row-click" key={subnet.id} onClick={() => onSelect(subnet)}><td className="mono"><strong>{subnet.cidr}</strong></td><td>{sites.find((site) => site.id === subnet.site_id)?.name || "Unassigned"}</td><td>{subnet.description || "—"}</td><td className="muted">{new Date(subnet.updated_at).toLocaleDateString()}</td>{canEdit || canDelete ? <td className="actions">{canEdit ? <button className="secondary" onClick={(event) => { event.stopPropagation(); open(subnet); }}>Edit</button> : null}{canDelete ? <button className="secondary danger" onClick={(event) => { event.stopPropagation(); void onDelete(subnet); }}>Delete</button> : null}</td> : null}</tr>)}</tbody></table>}</section>{formOpen ? <div className="modal"><div className="modal__backdrop" onClick={() => setFormOpen(false)} /><form className="modal__content" onSubmit={submit}><p className="eyebrow">{editing ? "Edit subnet" : "New subnet"}</p><h2 className="title">{editing ? editing.cidr : "Create a subnet"}</h2><label className="field"><span>CIDR</span><input value={cidr} onChange={(event) => setCidr(event.target.value)} placeholder="10.0.0.0/24" autoFocus /></label><label className="field"><span>Site</span><select value={siteId} onChange={(event) => setSiteId(event.target.value)}><option value="">Unassigned</option>{sites.map((site) => <option key={site.id} value={site.id}>{site.name}</option>)}</select></label><label className="field"><span>Description</span><input value={description} onChange={(event) => setDescription(event.target.value)} placeholder="Office network" /></label>{formError ? <div className="error">{formError}</div> : null}<div className="modal__actions"><button type="button" className="secondary" onClick={() => setFormOpen(false)}>Cancel</button><button className="primary" disabled={saving}>{saving ? "Saving…" : "Save subnet"}</button></div></form></div> : null}</main>;
}
