import { memo, useEffect, useMemo, useState } from "react";
import { api, type Requester } from "../api";
import type { IPAddress, KubernetesService, KubernetesServiceObservation, KubernetesServiceStatus, SiteStatistics, Subnet } from "../types";

const WINDOW = 256;
function parseCidr(cidr: string) { const [address, maskText] = cidr.split("/"); const mask = Number(maskText); const octets = address?.split(".").map(Number); if (!address || !Number.isInteger(mask) || mask < 0 || mask > 32 || !octets || octets.length !== 4 || octets.some((part) => !Number.isInteger(part) || part < 0 || part > 255)) return null; return { network: ((((octets[0] << 24) | (octets[1] << 16) | (octets[2] << 8) | octets[3]) >>> 0) & (mask === 0 ? 0 : (0xffffffff << (32 - mask)) >>> 0)) >>> 0, count: mask === 32 ? 1 : 2 ** (32 - mask) }; }
const ip = (value: number) => `${value >>> 24 & 255}.${value >>> 16 & 255}.${value >>> 8 & 255}.${value & 255}`;
const statusLabel: Record<KubernetesServiceStatus, string> = { matched: "Matched", unmatched: "Unmatched", ambiguous: "Ambiguous", no_usable_ip: "No usable IP" };
const deriveServiceStatus = (addressStatuses: (KubernetesServiceStatus | undefined)[], hasAddresses: boolean): KubernetesServiceStatus => {
	if (addressStatuses.includes("ambiguous")) return "ambiguous";
	if (addressStatuses.includes("no_usable_ip")) return "no_usable_ip";
	if (addressStatuses.includes("matched")) return "matched";
	if (addressStatuses.includes("unmatched")) return "unmatched";
	return hasAddresses ? "matched" : "unmatched";
};
const serviceStatus = (service: KubernetesService | KubernetesServiceObservation): KubernetesServiceStatus => {
	if (service.status) return service.status;
	if ("match_status" in service && service.match_status) return service.match_status;
	const addresses = "addresses" in service ? service.addresses : service.matched_addresses;
	return deriveServiceStatus(addresses.map((address) => address.match_status), addresses.length > 0);
};
const ServiceCard = ({ service, observation = false }: { service: KubernetesService | KubernetesServiceObservation; observation?: boolean }) => {
	const status = serviceStatus(service);
	const addresses = "addresses" in service ? service.addresses : service.matched_addresses;
	return <article className="kubernetes-service"><div className="kubernetes-service__heading"><strong title={`${service.namespace}/${service.name}`}>{service.namespace}/{service.name}</strong><span className="service-badge">{service.type}</span></div><div className="kubernetes-service__meta"><span>{service.source.name || service.source.key}</span>{service.dns_name ? <span className="mono" title={service.dns_name}>{service.dns_name}</span> : null}</div>{observation ? <div className="kubernetes-service__addresses">{addresses.length ? addresses.map((address, index) => <span className={`service-status service-status--${address.match_status || "unmatched"}`} key={`${address.kind}-${address.ip}-${index}`}>{address.kind}: {address.ip} · {statusLabel[address.match_status || "unmatched"]}</span>) : <span className="muted">No usable IP addresses</span>}</div> : null}<div className="kubernetes-service__ports">{service.ports.length ? service.ports.map((port, index) => <span className="port-badge" key={`${port.name || port.port}-${port.protocol}-${index}`}>{port.name ? `${port.name} ` : ""}{port.port}/{port.protocol}</span>) : <span className="muted">No declared ports</span>}</div><span className={`service-status service-status--${status}`} aria-label={`Service status: ${statusLabel[status]}`}>{statusLabel[status]}</span></article>;
};
const IpRow = memo(({ address, record, saving, onSave }: { address: string; record?: IPAddress; saving: boolean; onSave: (address: string, hostname: string) => void }) => { const [draft, setDraft] = useState(record?.hostname ?? ""); useEffect(() => setDraft(record?.hostname ?? ""), [record?.hostname]); return <article className="ip-card"><div className="ip-card__heading"><strong className="mono">{address}</strong><span className="muted">{record?.updated_at ? `Updated ${new Date(record.updated_at).toLocaleString()}` : "Untracked"}</span></div><label className="manual-hostname"><span>Manual hostname</span><input aria-label={`Manual hostname for ${address}`} value={draft} onChange={(event) => setDraft(event.target.value)} placeholder="(unset)" /></label><div><span className="field-label">Kubernetes Services</span><div className="kubernetes-services">{record?.kubernetes_services?.length ? record.kubernetes_services.map((service) => <ServiceCard key={`${service.source.key}:${service.uid}`} service={service} />) : <span className="muted">No discovered Services</span>}</div></div><button className="secondary ip-card__save" disabled={saving} onClick={() => onSave(address, draft)}>{saving ? "Saving…" : "Save hostname"}</button></article>; }, (a, b) => a.address === b.address && a.record?.id === b.record?.id && a.record?.hostname === b.record?.hostname && a.record?.updated_at === b.record?.updated_at && a.record?.kubernetes_services === b.record?.kubernetes_services && a.saving === b.saving);

type Props = { subnet: Subnet; site?: SiteStatistics; requester: Requester; canEdit: boolean; canDelete: boolean; onBack: () => void; onRefreshUsage: () => void };
export default function SubnetDetailView({ subnet, site, requester, canEdit, canDelete, onBack, onRefreshUsage }: Props) {
	const [records, setRecords] = useState<IPAddress[]>([]); const [services, setServices] = useState<KubernetesServiceObservation[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState<string | null>(null); const [windowStart, setWindowStart] = useState(0);
	useEffect(() => { setLoading(true); setError(null); void Promise.all([api.ips(requester, subnet.id), api.kubernetesServices(requester, subnet.id)]).then(([nextRecords, nextServices]) => { setRecords(nextRecords); setServices(nextServices); }).catch((err) => setError(err instanceof Error ? err.message : "Unable to load subnet details")).finally(() => setLoading(false)); }, [requester, subnet.id]);
	const parsed = useMemo(() => parseCidr(subnet.cidr), [subnet.cidr]); const max = parsed && parsed.count > WINDOW ? Math.floor((parsed.count - 1) / WINDOW) * WINDOW : 0; const start = Math.min(windowStart, max); const end = parsed ? Math.min(start + WINDOW, parsed.count) : 0; const addresses = useMemo(() => parsed ? Array.from({ length: end - start }, (_, index) => ip((parsed.network + start + index) >>> 0)) : [], [parsed, start, end]); const map = useMemo(() => new Map(records.map((record) => [record.ip, record])), [records]);
		const save = async (address: string, hostname: string) => { const existing = map.get(address); setSaving(address); try { if (existing && !hostname.trim()) { const response = await api.deleteIp(requester, subnet.id, existing.id); if (!response.ok) throw new Error("Unable to clear IP"); setRecords((current) => current.filter((record) => record.id !== existing.id)); } else { const saved = await api.saveIp(requester, subnet.id, existing, address, hostname); setRecords((current) => [saved, ...current.filter((record) => record.ip !== saved.ip)]); } onRefreshUsage(); } catch (err) { setError(err instanceof Error ? err.message : "Unable to save IP"); } finally { setSaving(null); } };
	return <main className="content"><button className="back-link" onClick={onBack}>← Back to subnets</button><div className="page-heading"><div><p className="eyebrow">Subnet detail</p><h1 className="mono">{subnet.cidr}</h1><p className="muted">{site ? `Owned by ${site.name}` : "Unassigned site"} · {subnet.description || "No description"}</p></div><div className="detail-count"><strong>{parsed?.count.toLocaleString() ?? "—"}</strong><span className="muted">total addresses</span></div></div>{error ? <div className="error" role="alert">{error}</div> : null}<section className="card kubernetes-services-panel"><div className="section-heading"><div><p className="eyebrow">Discovery</p><h2>Kubernetes Services</h2><p className="muted">Observed in the subnet’s site context. Match details appear on each Service.</p></div><span className="pill">{services.length} observed</span></div>{loading ? <p className="muted" aria-live="polite">Loading Services…</p> : services.length ? <div className="kubernetes-service-list">{services.map((service) => <ServiceCard key={`${service.source.key}:${service.uid}`} service={service} observation />)}</div> : <p className="muted">No discovered Services for this subnet site.</p>}</section><section className="card"><div className="table-toolbar"><div><h2 className="panel__title">IP addresses</h2>{!loading && parsed ? <span className="muted">Showing {start + 1}–{end} of {parsed.count.toLocaleString()}</span> : null}</div>{max ? <div className="button-group"><button className="secondary" onClick={() => setWindowStart((value) => Math.max(value - WINDOW, 0))} disabled={!start}>Previous</button><button className="secondary" onClick={() => setWindowStart((value) => Math.min(value + WINDOW, max))} disabled={start >= max}>Next</button></div> : null}</div>{loading ? <p className="muted" aria-live="polite">Loading IPs…</p> : !parsed ? <div className="error">Cannot render IPs for this CIDR.</div> : <div className="ip-card-list">{addresses.map((address) => <IpRow key={address} address={address} record={map.get(address)} saving={saving === address} onSave={(value, hostname) => void save(value, hostname)} />)}</div>}</section></main>;
}
